In [1]:
from classes.Individual import Individual

In [2]:
i = Individual(4,12)

In [3]:
test = Individual(10,5)
test.values

array([ 0.31408759, -0.88514749,  0.14142587,  0.11204154, -0.45584561,
       -0.75830902, -0.85723591, -0.64136316, -0.18413509,  0.12967312])

In [4]:
from classes.Population import Population

In [5]:
def eval_fun(values):
    return sum(values)

In [6]:
import numpy as np
eval_fun(np.array([2,2,2]))

6

In [7]:
p = Population(5,10,0, eval_fun)

In [8]:
p.individuals[3].values

array([ 0.78207656,  0.68794459, -0.02203637,  0.04478256, -0.8493654 ,
       -0.48010195,  0.41131883, -0.30678869,  0.69339747, -0.6888057 ])

In [12]:
p.all_fitnesses()

array([ 0.7261917 ,  0.12654222, -2.92344644,  0.27242191,  1.22585187])

In [10]:
p.evaluate_fitness()

In [11]:
p.individuals[3].fitness

0.272421906625262

In [13]:
from classes.Mutation import CustomSigma

In [14]:
c = CustomSigma(0.1,0.05)

In [15]:
c.mutate(i)

In [16]:
i.values

array([ 0.77305329,  0.71446365, -0.28235819, -1.23166802])

In [17]:
c.mutate(i)
i.values

array([ 0.59546502,  1.83040911,  0.6508145 , -1.43656025])

In [20]:
population = Population(5,10,0, eval_fun)
evals = population.evaluate_fitness()

In [22]:
evals