In [1]:
from classes.Individual import Individual

In [2]:
i = Individual(4,12)

In [3]:
test = Individual(10,5)
test.values

array([0.88748997, 0.34266449, 0.03687301, 0.47467503, 0.63875425,
       0.55550167, 0.07159658, 0.67835106, 0.01698126, 0.82132454])

In [4]:
from classes.Population import Population

In [5]:
def eval_fun(values):
    return sum(values)

In [6]:
import numpy as np
eval_fun(np.array([2,2,2]))

6

In [7]:
p = Population(5,10,0, eval_fun)

In [8]:
p.individuals[3].values

array([0.80555431, 0.62726677, 0.80835771, 0.71076878, 0.88543311,
       0.90850626, 0.11427809, 0.31565658, 0.05437181, 0.14534888])

In [9]:
p.best_fitness()

-inf

In [10]:
p.evaluate_fitness()

In [11]:
p.individuals[3].fitness

5.375542284404247

In [12]:
from classes.Mutation import CustomSigma

In [13]:
c = CustomSigma(0.1,0.05)

In [14]:
c.mutate(i)

In [16]:
i.values

array([0.90873775, 0.38091257, 0.33643985, 0.53736001])

In [17]:
c.mutate(i)
i.values

array([-1.23838049,  0.59543478, -0.48657737,  0.54732399])